# Generated by Django 4.1.3 on 2022-12-07 09:45

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200604_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
            ],
        ),
        migrations.RemoveField(
            model_name='dinner_platter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regular_pizza',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='id',
        ),
        migrations.AlterField(
            model_name='dinner_platter',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
