# Generated by Django 4.1.3 on 2022-12-07 10:02

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_remove_dinner_platter_id_remove_food_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='cc_number',
            field=creditcards.models.CardNumberField(max_length=25, primary_key=True, serialize=False, verbose_name='card number'),
        ),
    ]
