# Generated by Django 4.1.3 on 2022-12-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_payment_id_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular_pizza',
            name='test',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
