# Generated by Django 4.1.3 on 2022-12-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_regular_pizza_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardrsa', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='order_price',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.user'),
        ),
        migrations.AlterField(
            model_name='user_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.user'),
        ),
    ]
